### ISSUE TITLE
Embed media queries inside selectors

### ISSUE THREAD

**Issue by Flamov** [sfregolina/product-page#2]
Instead of:

```scss
h1 {
   font-size: 1rem;
}

@media (max-width: 42em) {
   h1 {
      font-size: 1rem;
   }
}
```

You can do:

```scss
h1 {
  font-size: 1rem;

  @media (max-width: 42em) {
    font-size: 1rem;
  }
}
```
